ackermann_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : drive
        timeout : 0.2
        priority: 10
      keyboard:
        topic   : keyboard_teleop
        timeout : 0.2
        priority: 100